# Generated by Django 5.0.3 on 2024-03-28 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_rename_stage_lead_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='notes',
            new_name='lead_description',
        ),
    ]
