# Generated by Django 5.0.3 on 2024-03-28 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_rename_notes_lead_lead_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='user',
        ),
    ]
